### ISSUE TITLE
Bug: Create reservation success dialog always dispalyed

### ISSUE THREAD

**Issue by juliaringler** [SafeMarket-WirVsVirus/frontend-enduser#10]
When creating a reservation we do not check the backend result but just display a success alert even though we received an error by the backend

**Comment by Johannes11833** [comment]
Vielleicht auch eine Error-snackbar  wenns nicht klappt? ;)

**Comment by LukkyLukke** [comment]
isnt this already implemented with the reservation fail dialog?

**Comment by juliaringler** [comment]
I was not able to test it yet since yesterday (but merged it anyway)

**Comment by LukkyLukke** [comment]
Thats my kind of optimism!
It works though
