### ISSUE TITLE
Remove Live-Tracking for Now and Improve Display of Selected Store Type

### ISSUE THREAD

**Issue by juliaringler** [SafeMarket-WirVsVirus/frontend-enduser#108]
* Do not remove the whole code for the live tracking filtering, but remove UI as well as the filtering in the map_bloc
* display a Chip (https://www.material.io/components/chips/) with the selected store type and label

**Comment by LukkyLukke** [comment]
![photo_2020-04-12_01-19-43](https://user-images.githubusercontent.com/28596423/79056920-c22fc480-7c5b-11ea-8bcc-b40ca0430ed8.jpg)
