### ISSUE TITLE
Deleting a reservation bug

### ISSUE THREAD

**Issue by ConstantinB9** [SafeMarket-WirVsVirus/frontend-enduser#35]
When deleting a reservation on the Reservation List Page, the following error occurs:

The getter 'id' was called on null.
Receiver: null
Tried calling: id

**Comment by juliaringler** [comment]
We need a backend change for this, I create a ticket for this in the backend repo

**Comment by juliaringler** [comment]
https://github.com/SafeMarket-WirVsVirus/backend/issues/2
