### ISSUE TITLE
Sort reservations by dates

### ISSUE THREAD

**Issue by Johannes11833** [SafeMarket-WirVsVirus/frontend-enduser#53]

**Comment by juliaringler** [comment]
Update: Not ordered or probably ordered by reservation id :D
----I made some reservations for my phone (location id 7 works) and received an ordered list by the backend----

**Comment by Johannes11833** [comment]
I repeatedly tested this with the one supermarket in Berlin and can confirm that it's sorted by the order in which you reserved the different time slots (which is equivalent to the order id)
