### ISSUE TITLE
Imprint Page?

### ISSUE THREAD

**Issue by juliaringler** [SafeMarket-WirVsVirus/frontend-enduser#69]
Do we need an imprint page?

**Comment by Johannes11833** [comment]
I was trying to get this to work using showAboutDialog but unfortunately the app crashes as soon as I click on "view licenses" without any useful error messages.

**Comment by Johannes11833** [comment]
Do we want to use my showAboutDialog  approach even though it shows a bunch of other libraries or should we implement our own solution?

**Comment by juliaringler** [comment]
https://file000.flaticon.com/downloads/license/license.pdf
